
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_iae
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  admin:
    build:
      context: ./Admin
    container_name: admin_app
    ports:
      - "8000:8000"
    working_dir: /var/www
    volumes:
      - ./Admin:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: EAI_admin
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8000"

  user:
    build:
      context: ./User
    container_name: user_app
    ports:
      - "8001:8001"
    working_dir: /var/www
    volumes:
      - ./User:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: EAI_user
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8001"

volumes:
  mysql_data:
